services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html/app:cached
      - ./routes:/var/www/html/routes:cached
      - ./database:/var/www/html/database:cached
      - ./config:/var/www/html/config:cached
      - ./resources:/var/www/html/resources:cached
      - /var/www/html/vendor
      - /var/www/html/node_modules
    ports:
      - "9001:9000"
    command: php-fpm
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./public:/var/www/html/public:cached
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    networks:
      - laravel_network
    restart: unless-stopped

  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite
    volumes:
      - ./resources:/app/resources:cached
      - ./public:/app/public:cached
    environment:
      - CHOKIDAR_USEPOLLING=false
      - NODE_ENV=development
    ports:
      - "5173:5173"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
    networks:
      - laravel_network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  laravel_network:
    driver: bridge